### PR TITLE
Major cleanup

### PR DESCRIPTION
**Pull request by ghengeveld**
- Modern ES syntax (classes instead of manual prototype inheritance)
- Dropped Travis config (tried running on Circle, doesn't work out of the box)
- Updated README, package.json etc.

### CODE REVIEW

**Comment by tmeasday** [comment]
Wow, cool. I guess this makes it harder to take patches from upstream, but there haven't been a lot of those!

Are we running the tests on CI now?

**Review by tmeasday — APPROVED** [review]

**Comment by tmeasday** [comment]
We should probably check/add tests for the code changes we made (which are to support this: https://github.com/chromaui/chromatic/pull/1457). I might need to give you a bit more context there.

**Comment by ghengeveld** [comment]
Added some more work, specifically restoring / cleaning up the CLI support and changing from a callback to a Promise-based API. Please give it another look.

**Comment by tmeasday** [comment]
LGTM

**Pull request merged**
