### PR TITLE
Fetch upstream change which resolves axios security vulnerability

### PR DESCRIPTION
**Pull request by adayNU**
Resolves https://github.com/advisories/GHSA-cph5-m8f7-6c5x

### CODE REVIEW

**Comment by adayNU** [comment]
I think @tmeasday is the right person to tag here?

**Comment by tmeasday** [comment]
Thanks @adayNU

**Comment by tmeasday** [comment]
We will try and get this released ASAP.

**Comment by ghengeveld** [comment]
Released as v2.0.4.

**Pull request merged**
